class CollectionName:
    """Collection Name"""

    PATIENTS = "PYTHON_TEST_PATIENTS"
    ELIGIBILITY = "PYTHON_TEST_ELIGIBILITY"
    SUBSCRIBER = "PYTHON_TEST_SUBSCRIBER"
    ENROLLEE = "PYTHON_TEST_ENROLLEE"

    PROVIDER = "PYTHON_TEST_PROVIDER"
    AUTHORIZATION = "PYTHON_TEST_AUTHORIZATION"
    CLAIM = "PYTHON_TEST_CLAIM"
    BILLING = "PYTHON_TEST_BILLING"
    BILLING_DETAIL = "PYTHON_TEST_BILLING_DETAIL"

    DUMP_ELIGIBILITY = "PYTHON_TEST_DUMP_ELIGIBILITY"
    DUMP_ENROLLEES = "PYTHON_TEST_DUMP_ENROLLEES"
    DUMP_PROVIDER_CLAIM = "PYTHON_TEST_DUMP_PROVIDER_CLAIM"

    # PROVIDER_CLAIMS = "providerClaims"
    PROVIDER_CLAIMS = "PYTHON_TEST_PROVIDER_CLAIMS"

    DOCUMENTS = "PYTHON_TEST_DOCUMENTS"

    PRODUCTS = "products"

    PYTHON_TEST_THERAPY_NOTES = "PYTHON_TEST_THERAPY_NOTES"

    RECEIPTS = "receipts"
    RECEIPT_DETAILS = "receiptDetails"
    INVOICE_BILLINGS = "invoiceBillings"
    INVOICE_BILLING_DETAILS = "invoiceBillingDetails"
    INVOICE_PAYMENT_RECEIPTS = "invoicePaymentReceipts"

    ARDB_DUMP_INVOICE_BILLINGS = "ARDB_BILLING"
    ARDB_DUMP_INVOICE_BILLING_DETAILS = "ARDB_BILLING_DETAIL"
    ARDB_DUMP_RECEIPTS = "ARDB_RECEIPTS"
    ARDB_DUMP_RECEIPT_DETAILS = "ARDB_RECEIPTS_DETAIL"
    ARDB_DUMP_AUTHORIZATIONS = "ARDB_AUTH"

    THERAPY_ENROLLEE = "enrollees"
    THERAPY_PATIENT = "patients"
    THERAPY_SUBSCRIBER = "subscribers"
    THERAPY_ELIGIBILITY = "eligibilities"

    THERAPY_DOCUMENTS = "documents"
    THERAPY_NOTES = "therapyNotes"
