class CollectionName:
    """Collection Name"""

    PATIENTS = "PYTHON_TEST_PATIENTS"
    ELIGIBILITY = "PYTHON_TEST_ELIGIBILITY"
    SUBSCRIBER = "PYTHON_TEST_SUBSCRIBER"
    ENROLLEE = "PYTHON_TEST_ENROLLEE"
    PROVIDER = "PYTHON_TEST_PROVIDER"
    AUTHORIZATION = "PYTHON_TEST_AUTHORIZATION"
    CLAIM = "PYTHON_TEST_CLAIM"
    BILLING = "PYTHON_TEST_BILLING"
    BILLING_DETAIL = "PYTHON_TEST_BILLING_DETAIL"

    DUMP_ELIGIBILITY = "PYTHON_TEST_DUMP_ELIGIBILITY"
    DUMP_ENROLLEES = "PYTHON_TEST_DUMP_ENROLLEES"
    DUMP_PROVIDER_CLAIM = "PYTHON_TEST_DUMP_PROVIDER_CLAIM"

    PROVIDER_CLAIMS = "providerClaims"

    DOCUMENTS = "documents"
