from enum import Enum


class SheetName(str, Enum):
    """Excel sheet name enumeration"""

    INVOICE_BILLING = "BILLING"
    AUTHORIZATION = "AUTH"
    INVOICE_BILLING_DETAIL = "BILLING DETAIL"
    RECEIPT = "RECEIPTS"
    RECEIPT_DETAIL = "RECEIPTS DETAIL"
    ENROLLEES = "ENROLLEES"
    ELIGIBILITY = "ELIGIBILITY"
    EXPECTED_AMOUNT = "EXPECTED_AMOUNTS"
    BILLING_FILE = "BILLING_FILES"
    THIRD_PARTY_ADMINISTRATOR = "THIRD_PARTY_ADMINISTRATORS"
    PROVIDER_CLAIM = "CLAIMS"
    MARKET_CLAIM = "MARKET"
    PRODUCTS = "PRODUCTS"
    INSURER = "INSURER"
    BILLABLE_PRODUCTS = "BILLABLE PRODUCTS"

    # Provider Directory
    PD_PROVIDERS = "Providers"
    PD_LOCATIONS = "Locations"
    PD_PAYEES = "Payees"
    PD_PAYEE_DETAILS = "Payees_Detail"
    PD_PROVIDER_SUPPLEMENTAL = "Prov_Supplemental_Identifiers"
    PD_PAYEE_EFT_DETAILS = "Payees_EFT_Detail"
    PD_NETWORK_REIMBURSEMENT = "NR"
    PD_REIMBURSEMENT_SCHEDULE = "RS"
    PD_FEE_SCHEDULE = "FS"
