from enum import Enum


class SheetName(str, Enum):
    """Excel sheet name enumeration"""

    INVOICE_BILLING = "BILLING"
    AUTHORIZATION = "AUTH"
    INVOICE_BILLING_DETAIL = "BILLING DETAIL"
    RECEIPT = "RECEIPTS"
    RECEIPT_DETAIL = "RECEIPTS DETAIL"
    ELIGIBILITY = "ELIGIBILITY"
    EXPECTED_AMOUNT = "EXPECTED_AMOUNTS"
    BILLING_FILE = "BILLING_FILES"
    THIRD_PARTY_ADMINISTRATOR = "THIRD_PARTY_ADMINISTRATORS"
    PROVIDER_CLAIM = "CLAIMS"
    MARKET_CLAIM = "MARKET"
    PRODUCTS = "PRODUCTS"
    INSURER = "INSURER"
    BILLABLE_PRODUCTS = "BILLABLE PRODUCTS"
