SELECTED_ENROLLEE_COLS = [
    "EN_ENROLLEE_ID",
    "LAST_NAME",
    "FIRST_NAME",
    "MIDDLE_NAME",
    "NAME_PREFIX",
    "NAME_SUFFIX",
    "ADDRESS1",
    "ADDRESS2",
    "CITY",
    "STATE",
    "ZIP",
    "ZIP_4",
    "COUNTY_ID",
    # "ADDRESS_CODE",
    # "EMAIL",
    "DOB",
    # "BIRTH_SEQUENCE",
    # "DEATH_DATE",
    "GENDER",
    # "ETHNICITY_CODE",
    # "CITIZENSHIP_STATUS_CODE",
    "SS_NUMBER",
    # "EN_NOTES",
    "EN_CREATION_DATE",
    "EN_LAST_MODIFIED_DATE_TIME",
]


SELECTED_ENROLLEE_COLS_RENAMED = {
    "EN_ENROLLEE_ID": "ENROLLEE_ID",
    "EN_CREATION_DATE": "CREATION_DATE",
    "EN_LAST_MODIFIED_DATE_TIME": "LAST_MODIFIED_DATE_TIME",
}


SELECTED_SUBSCRIBER_COLS = [
    "EL_INSURED_ENROLLEE_ID",
    "SUBSCRIBER_ID",
    "EFFECTIVE_DATE",
    "TERMINATION_DATE",
    "PREMIUM_GROUP_ID",
    "PREMIUM_GROUP_DEPARTMENT_ID",
    "EL_CREATION_DATE",
    "EL_LAST_MODIFIED_DATE_TIME",
]


SELECTED_SUBSCRIBER_COLS_RENAMED = {
    "EL_INSURED_ENROLLEE_ID": "INSURED_ENROLLEE_ID",
    "EL_CREATION_DATE": "CREATION_DATE",
    "EL_LAST_MODIFIED_DATE_TIME": "LAST_MODIFIED_DATE_TIME",
}


SELECTED_PATIENT_COLS = [
    "EL_ENROLLEE_ID",
    "SUBSCRIBER_ID",
    "MEMBER_ID",
    "RELATIONSHIP_CODE",
    "EL_CREATION_DATE",  # created date
    "EL_LAST_MODIFIED_DATE_TIME",  # updated date
]


SELECTED_PATIENT_COLS_RENAMED = {
    "EL_ENROLLEE_ID": "ENROLLEE_ID",
    "EL_CREATION_DATE": "CREATION_DATE",
    "EL_LAST_MODIFIED_DATE_TIME": "LAST_MODIFIED_DATE_TIME",
}


SELECTED_ELIGIBILITY_COLS = [
    "EL_ENROLLEE_ID",
    "PRODUCT_ID",
    "EFFECTIVE_DATE",
    "TERMINATION_DATE",
    "SUBSCRIBER_ID",
    "MEMBER_ID",
    "PREMIUM_GROUP_ID",
    "PREMIUM_GROUP_DEPARTMENT_ID",
    "EL_INSURED_ENROLLEE_ID",
    "BENEFIT_STATUS_CODE",
    "RELATIONSHIP_CODE",
    "MARITAL_STATUS",
    "EL_CREATION_DATE",
    "EL_LAST_MODIFIED_DATE_TIME",
]


SELECTED_ELIGIBILITY_COLS_RENAMED = {
    "EL_ENROLLEE_ID": "ENROLLEE_ID",
    "EL_INSURED_ENROLLEE_ID": "INSURED_ENROLLEE_ID",
    "EL_CREATION_DATE": "CREATION_DATE",
    "EL_LAST_MODIFIED_DATE_TIME": "LAST_MODIFIED_DATE_TIME",
}


MISSING_ELIGIBILITY_MIGRATE_ETL_DATA_FRAME_TYPE = {
    "EL_ENROLLEE_ID": str,
    "PRODUCT_ID": str,
    "EFFECTIVE_DATE": str,
    "TERMINATION_DATE": str,
    "SUBSCRIBER_ID": str,
    "MEMBER_ID": str,
    "PREMIUM_GROUP_ID": str,
    "PREMIUM_GROUP_DEPARTMENT_ID": str,
    "EL_INSURED_ENROLLEE_ID": str,
    "EMPLOYMENT_STATUS": str,
    "EMPLOYMENT_EFFECTIVE_DATE": str,
    "EMPLOYMENT_TERMINATION_DATE": str,
    "BENEFIT_STATUS_CODE": str,
    "RELATIONSHIP_CODE": str,
    "MARITAL_STATUS": str,
    "STUDENT_STATUS_CODE": str,
    "HANDICAP_FLAG": str,
    "LEVEL_OF_CARE_ID": str,
    "LATE_ENROLLEE_FLAG": str,
    "WAITING_PERIOD_CREDIT": str,
    "ADD_REASON_CODE": str,
    "ADD_REASON_EVENT_DATE": str,
    "TERMINATION_REASON_CODE": str,
    "TERMINATION_REASON_EVENT_DATE": str,
    "EL_NOTES": str,
    "CLIENT_MCO_ID": str,
    "CLIENT_PROGRAM_CODE": str,
    "CLIENT_RATE_CODE": str,
    "OTHER_INFO1": str,
    "OTHER_INFO2": str,
    "OTHER_INFO3": str,
    "EL_CREATION_DATE": str,
    "EL_DOMAIN_SOURCE_ID": str,
    "EL_LAST_MODIFIED_DATE_TIME": str,
    "PAID_THROUGH_DATE": str,
    "PAID_THROUGH_GRACE_PERIOD": str,
    "HASH": str,
    "EN_ENROLLEE_ID": str,
    "LAST_NAME": str,
    "FIRST_NAME": str,
    "MIDDLE_NAME": str,
    "NAME_PREFIX": str,
    "NAME_SUFFIX": str,
    "ADDRESS1": str,
    "ADDRESS2": str,
    "CITY": str,
    "STATE": str,
    "ZIP": str,
    "ZIP_4": str,
    "COUNTY_ID": str,
    "ADDRESS_CODE": str,
    "EMAIL": str,
    "DOB": str,
    "BIRTH_SEQUENCE": str,
    "DEATH_DATE": str,
    "GENDER": str,
    "ETHNICITY_CODE": str,
    "CITIZENSHIP_STATUS_CODE": str,
    "SS_NUMBER": str,
    "EN_NOTES": str,
    "EN_CREATION_DATE": str,
    "EN_DOMAIN_SOURCE_ID": str,
    "EN_GEO": str,
    "EN_HASH": str,
    "EN_LAST_MODIFIED_DATE_TIME": str,
    "PREFERRED_CONTACT_METHOD": str,
    "RACE_ETHNICITY_CODE": str,
    "EOB_COMMUNICATION_METHOD": str,
    "ID_CARD_COMMUNICATION_METHOD": str,
    "LETTER_COMMUNICATION_METHOD": str,
}
