ELIGIBILITY_MIGRATE_ETL_DATA_FRAME_TYPE = {
    "ENROLLEE_ID": str,
    "PRODUCT_ID": str,
    "EFFECTIVE_DATE": str,
    "TERMINATION_DATE": str,
    "SUBSCRIBER_ID": str,
    "MEMBER_ID": str,
    "PREMIUM_GROUP_ID": str,
    "PREMIUM_GROUP_DEPARTMENT_ID": str,
    "INSURED_ENROLLEE_ID": str,
    "BENEFIT_STATUS_CODE": str,
    "RELATIONSHIP_CODE": str,
    "MARITAL_STATUS": str,
    "CREATION_DATE": str,
    "LAST_MODIFIED_DATE_TIME": str,
}


ELIGIBILITY_MIGRATE_COLS = [
    "ENROLLEE_ID",
    "PRODUCT_ID",
    "EFFECTIVE_DATE",
    "TERMINATION_DATE",
    "SUBSCRIBER_ID",
    "MEMBER_ID",
    "PREMIUM_GROUP_ID",
    "PREMIUM_GROUP_DEPARTMENT_ID",
    "INSURED_ENROLLEE_ID",
    "BENEFIT_STATUS_CODE",
    "RELATIONSHIP_CODE",
    "MARITAL_STATUS",
    "CREATION_DATE",
    "LAST_MODIFIED_DATE_TIME",
]


SUBSCRIBER_MIGRATE_COLS = [
    "INSURED_ENROLLEE_ID",
    "SUBSCRIBER_ID",
    "EFFECTIVE_DATE",
    "TERMINATION_DATE",  # employment
    "PREMIUM_GROUP_ID",
    "PREMIUM_GROUP_DEPARTMENT_ID",  # premium group
    "CREATION_DATE",
    "LAST_MODIFIED_DATE_TIME",
]


PATIENT_MIGRATE_COLS = [
    "ENROLLEE_ID",
    "SUBSCRIBER_ID",
    "MEMBER_ID",
    "RELATIONSHIP_CODE",
    "CREATION_DATE",  # created date
    "LAST_MODIFIED_DATE_TIME",  # updated date
]
