from typing import TypedDict


RECEIPT_DETAIL_NOTE_MIGRATE_COLS = [
    "RECEIPT_DETAIL_ID",
    "RECEIPT_ID",
    "INVOICE_BILLING_ID",
    "INVOICE_ITEM_NUMBER",
    "PAYMENT_NOTES",
    "DATE_ENTERED",
]
